Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-12, with the labels that each got.

#408 [Changelog] Update for Sprint 100
  CHANGELOG.md
Labels: documentation

#413 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#409 Exclude already attached VMs from the volume attachment form
  app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
Labels: bug

#415 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#418 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
