Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-07, with the labels that each got.

#313 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#316 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-4
  CHANGELOG.md
Labels: documentation

#317 Bump fog-openstack to version 0.1.27
  manageiq-providers-openstack.gemspec
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: bug

#314 Instances workflow: Allow flavors with disk size of 0
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
Labels: enhancement

#319 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#321 [Gaprindashvili] fog openstack bump to version 0.1.27
  manageiq-providers-openstack.gemspec
Labels: blocker, bug

#309 Add template decorator
  app/decorators/manageiq/providers/openstack/cloud_manager/template_decorator.rb
Labels: bug, wip
