Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-08, with the labels that each got.

#326 Infra Discovery: support for SSL
  app/models/manageiq/providers/openstack/discovery.rb
  spec/models/manageiq/providers/openstack/discovery_spec.rb
Labels: enhancement, gaprindashvili/yes

#328 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation

#329 Flavors: always include private flavors
  app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/openstack/refresh_parser_common/flavors.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: bug

#322 Require hostname if provider is enabled
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug

#330 Catch Bad Request responses in safe_call
  app/models/manageiq/providers/openstack/refresh_parser_common/helper_methods.rb
Labels: bug, fine/yes, gaprindashvili/yes

#333 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#337 Move Inventory to ManageIQ::Providers
  app/models/manageiq/providers/openstack/inventory.rb
  app/models/manageiq/providers/openstack/inventory/collector.rb
  app/models/manageiq/providers/openstack/inventory/parser.rb
  app/models/manageiq/providers/openstack/inventory/persister.rb
Labels: refactoring

#338 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-5
  CHANGELOG.md
Labels: documentation

#339 Use nil as initialiser for @orchestration_stacks to prevent looping.
  app/models/manageiq/providers/openstack/inventory/collector.rb
  app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector/network_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
Labels: bug, performance
