Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-05, with the labels that each got.

#279 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation

#285 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#287 [Changelog] Update for Sprint 85
  CHANGELOG.md
Labels: documentation

#290 Fix targeted refresh builder params for network objects
  app/models/manageiq/providers/openstack/inventory/persister/target_collection.rb
  lib/vcr_recorder.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
Labels: bug

#293 Friendly error message for HTTP 503
  app/models/manageiq/providers/openstack/helper_methods.rb
Labels: blocker, bug, gaprindashvili/yes
