Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-04, with the labels that each got.

#261 BZ1545322: metrics capture shouldn't fail on nil NetworkPort ems_ref
  app/models/manageiq/providers/openstack/base_metrics_capture.rb
Labels: bug, gaprindashvili/yes

#264 Fixes unfriendly message when adding network for unavailable provider
  app/models/manageiq/providers/openstack/helper_methods.rb
Labels: bug

#242 Ensure Openstack uses its own CinderManager
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/storage_manager/cinder_manager.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: unmergeable

#267 Make Gnocchi default granularity configurable in Settings
  config/settings.yml
  lib/manageiq/providers/openstack/legacy/openstack_handle/metric_delegate.rb
Labels: bug, gaprindashvili/yes

#270 [Changelog] Update for Sprint 83
  CHANGELOG.md
Labels: documentation

#271 translate_exceptions: Parse errors out of fog responses
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: bug, gaprindashvili/yes

#273 [Gaprindashvili] Remove obsolete VCRs for very old versions of Openstack
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_juno_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_keystone_v3_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_juno.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_juno_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_juno_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_kilo_with_errors.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: blocker, test, unmergeable

#274 [GAPRINDASHVILI] Implement Graph Refresh for the Cinder Manager
  app/models/manageiq/providers/openstack/builder.rb
  app/models/manageiq/providers/openstack/cinder_manager_mixin.rb
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector.rb
  app/models/manageiq/providers/openstack/inventory/collector/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
  app/models/manageiq/providers/openstack/inventory/parser.rb
  app/models/manageiq/providers/openstack/inventory/parser/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister.rb
  app/models/manageiq/providers/openstack/inventory/persister/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/target_collection.rb
  app/models/manageiq/providers/openstack/inventory_collection_default/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory_collection_default/storage_manager.rb
  app/models/manageiq/providers/openstack/refresh_parser_common/helper_methods.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/refresh_parser.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/refresher.rb
  config/settings.yml
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb
  spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: blocker, bug

#281 Add Openstack CinderManager EventCatcher
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
  app/models/manageiq/providers/openstack/inventory/persister/target_collection.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher/runner.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_parser.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb
  config/settings.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: blocker, gaprindashvili/yes

#280 Catch Fog::Errors::NotFound in OpenstackHandle.handled_list
  lib/manageiq/providers/openstack/legacy/openstack_handle/handled_list.rb
Labels: blocker, bug, gaprindashvili/yes

#282 Move CinderManager inventory classes
  app/models/manageiq/providers/openstack/builder.rb
  app/models/manageiq/providers/openstack/inventory/collector.rb
  app/models/manageiq/providers/openstack/inventory/collector/cinder_manager.rb
  app/models/manageiq/providers/openstack/inventory/parser.rb
  app/models/manageiq/providers/openstack/inventory/parser/cinder_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister.rb
  app/models/manageiq/providers/openstack/inventory/persister/cinder_manager.rb
Labels: blocker, gaprindashvili/yes

#283 [GAPRINDASHVILI] Add Openstack CinderManager EventCatcher
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
  app/models/manageiq/providers/openstack/inventory/persister/target_collection.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher/runner.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_parser.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb
  config/settings.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: blocker
