Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-09, with the labels that each got.

#342 Filter Keystone Projects by domain_id
  lib/manageiq/providers/openstack/legacy/openstack_handle/identity_delegate.rb
Labels: bug

#354 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#355 Make `default_security_group` visible in the API
  app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
Labels: enhancement

#362 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#366 Direct attribute access for `cloud_volume_types` via cloud_tenants API
  app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
Labels: hammer/yes
