Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-11, with the labels that each got.

#383 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Openstack.po
  locale/fr/ManageIQ_Providers_Openstack.po
  locale/ja/ManageIQ_Providers_Openstack.po
  locale/pt_BR/ManageIQ_Providers_Openstack.po
  locale/zh_CN/ManageIQ_Providers_Openstack.po
Labels: internationalization

#385 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#381 [Changelog] Add Sprint 97 and Hammer Beta1 updates
  CHANGELOG.md
Labels: documentation

#392 [Changelog] Update for Sprint 98, H-B2, and G6
  CHANGELOG.md
Labels: documentation

#374 Parallelize OpenstackHandle
  app/models/manageiq/providers/openstack/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/compute_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/network_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/volume_delegate.rb
  spec/legacy/openstack_handle/handle_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Labels: unmergeable

#382 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation

#391 [HAMMER] Bump fog-openstack to v0.1.29
  manageiq-providers-openstack.gemspec
Labels: blocker, bug

#399 New Cloud provider: Fix event creds validation for AMQP
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: bug, fine/yes, hammer/yes

#397 Service dialog for orchestration template needs tenant selection
  app/models/manageiq/providers/openstack/cloud_manager/orchestration_template.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#401 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#380 Check if host create event exists and assign host to it
  app/models/manageiq/providers/openstack/infra_manager/event_parser.rb
  app/models/manageiq/providers/openstack/infra_manager/host.rb
  app/models/manageiq/providers/openstack/infra_manager/refresher.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
Labels: bug

#403 Add explicit runtime dependency on the "parallel" gem
  manageiq-providers-openstack.gemspec
Labels: blocker, bug, hammer/yes

#404 Require 'parallel' in the OpenstackHandle
  lib/manageiq/providers/openstack/legacy/openstack_handle.rb
Labels: blocker, bug, hammer/yes

#402 Collect Panko events for all tenants.
  lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
Labels: blocker, gaprindashvili/yes, hammer/yes

#406 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
