Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-03, with the labels that each got.

#239 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#241 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#250 Correct network event target associations
  app/models/manageiq/providers/openstack/network_manager/event_target_parser.rb
  spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb
Labels: bug

#238 Filter openstack networks without subnets
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
  spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
Labels: bug, gaprindashvili/yes

#240 Dont return Storage Services if They arent present
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug, fine/yes, gaprindashvili/yes, smart state

#260 Fix parent subnet relationship
  app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb
Labels: blocker, bug, gaprindashvili/yes

#259 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation

#262 Default Event payload to empty Hash
  app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb
  app/models/manageiq/providers/openstack/infra_manager/event_parser.rb
  app/models/manageiq/providers/openstack/network_manager/event_parser.rb
Labels: blocker, bug, fine/yes, gaprindashvili/yes
