Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2018-10, with the labels that each got.

#367 [Gaprindashvili]Use empty name if only size provided
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
  spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#369 Don't use string interpolations inside gettext strings
  app/models/manageiq/providers/openstack/cloud_manager/flavor.rb
Labels: hammer/yes, internationalization

#372 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#376 Travis - change postgres to 9.5
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#373 BZ 1635635 Avoid uniqueness constraint violations in sync_users
  app/models/manageiq/providers/openstack/identity_sync_mixin.rb
Labels: blocker

#361 Parse containerized openstack services
  app/models/manageiq/providers/openstack/infra_manager/host.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
Labels: bug, enhancement, wip

#324 New Cloud provider: Fix event creds validation for AMQP
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes
