Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-03, with the labels that each got.

#446 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#449 Remove references to MiqPassword
  app/models/manageiq/providers/openstack/manager_mixin.rb
  spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Labels: technical debt

#450 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#453 Update supported ruby versions on Travis
  .travis.yml
Labels: test

#454 [Changelog] Update for Hammer-4
  CHANGELOG.md
Labels: documentation, hammer/yes

#457 Parse OpenStack Event Timestamps as UTC
  lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
Labels: bug, hammer/yes
