Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-07, with the labels that each got.

#480 The leaf class should be tested
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_worker_spec.rb
Labels: test

#481 Rerecord VCRs after factories change
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Labels: bug, test

#483 Add a rubocop channel to the codeclimate config
  .codeclimate.yml
Labels: dependencies

#484 Fix OpenStack services list with Podman
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: bug

#486 [Changelog] Update for Hammer-9
  CHANGELOG.md
Labels: documentation, hammer/yes

#488 Remove legacy refresh code
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/cloud_manager/refresh_parser.rb
  app/models/manageiq/providers/openstack/network_manager.rb
  app/models/manageiq/providers/openstack/network_manager/refresh_parser.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/refresh_parser.rb
  config/settings.yml
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb
Labels: cleanup, ivanchuk/no

#490 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
