Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-05, with the labels that each got.

#466 [Changelog] Update for Sprint 110
  CHANGELOG.md
Labels: documentation

#470 Change plugin common methods to class methods
  lib/manageiq/providers/openstack/engine.rb
Labels: refactoring

#469 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#471 [Changelog] Update for Hammer-6
  CHANGELOG.md
Labels: documentation

#472 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#474 Revert "Don't create a MIQ Snapshot record when creating an OSP Snapshot"
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: gaprindashvili/yes, hammer/yes
