Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-04, with the labels that each got.

#459 [Changelog] Update for Sprint 108
  CHANGELOG.md
Labels: documentation

#460 Update .travis.yml PostgreSQL version to 10
  .travis.yml
Labels: test

#461 [Changelog] Update for Hammer-5 release
  CHANGELOG.md
Labels: documentation

#462 Create instance snapshots with the owner's project scope
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug, changelog/yes
