Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-09, with the labels that each got.

#506 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#508 update_attributes deprecation
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations/guest.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations/power.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations/relocation.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
  app/models/manageiq/providers/openstack/infra_manager/host.rb
  spec/models/manageiq/providers/openstack/infra_manager/refresh_worker_spec.rb
Labels: technical debt

#509 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation

#511 Fix Snapshot create error message
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug
