Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-02, with the labels that each got.

#439 [Changelog] Update for Sprint 104
  CHANGELOG.md
Labels: documentation

#430 [HAMMER] Bump fog openstack
  manageiq-providers-openstack.gemspec
Labels: bug, gaprindashvili/backported

#440 Removal of static attributes in factories
  spec/factories/orchestration_template.rb
Labels: refactoring, test

#441 Add ConversionHost and ServiceTemplateTransformationPlan subclasses
  app/models/manageiq/providers/openstack/cloud_manager/conversion_host.rb
  app/models/manageiq/providers/openstack/cloud_manager/service_template_transformation_plan.rb
Labels: enhancement

#442 Remove old ManagerRefresher class
  app/models/manageiq/providers/openstack/cloud_manager/refresher.rb
  app/models/manageiq/providers/openstack/network_manager/refresher.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/refresher.rb
Labels: cleanup

#443 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation

#416 bug 1614567: Allow user to select Network Port for provisioning
  app/models/manageiq/providers/openstack/cloud_manager/provision/configuration.rb
  app/models/manageiq/providers/openstack/cloud_manager/provision/options_helper.rb
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow/dialog_field_validation.rb
  content/miq_dialogs/miq_provision_openstack_dialogs_template.yaml
  spec/models/manageiq/providers/openstack/cloud_manager/provision/configuration_spec.rb
Labels: enhancement

#444 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes
