Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-11, with the labels that each got.

#527 Remove zanata from README
  README.md
Labels: cleanup

#529 Subclass require_snapshot_for_scan? method
  app/models/manageiq/providers/openstack/cloud_manager/template.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm_or_template_shared.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm_or_template_shared/scanning.rb
Labels: refactoring, smart state

#528 Optionally symlink spec/manageiq during bin/setup
  bin/setup
Labels: enhancement

#530 Add and subclass scan_timeout_adjustment_multiplier method
  app/models/manageiq/providers/openstack/cloud_manager/vm_or_template_shared/scanning.rb
Labels: refactoring, smart state

#532 Add params_for_create and verify_credentials
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: enhancement

#535 Move OpenStack-specific part of vm_scan_spec.rb from the core repo
  spec/models/manageiq/providers/openstack/cloud_manager/vm_scan_spec.rb
Labels: refactoring, smart state, test

#533 Add codeowners
  .github/CODEOWNERS
Labels: documentation

#537 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/openstack/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/cloud_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/openstack/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/openstack/infra_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/infra_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/openstack/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/openstack/network_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/network_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/openstack/network_manager/refresh_worker.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher.rb
Labels: refactoring

#539 Remove the require_nested call for removed refresh worker
  app/models/manageiq/providers/openstack/network_manager.rb
Labels: bug

#521 Fix Image targeted refresh
  app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb
  spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
Labels: bug, hammer/yes, ivanchuk/yes

#536 Remove ems_ref_obj
  app/models/manageiq/providers/openstack/infra_manager/event_parser.rb
  app/models/manageiq/providers/openstack/infra_manager/host.rb
  app/models/manageiq/providers/openstack/infra_manager/host/operations.rb
  app/models/manageiq/providers/openstack/infra_manager/metrics_capture.rb
  app/models/manageiq/providers/openstack/infra_manager/orchestration_stack.rb
  app/models/manageiq/providers/openstack/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
  spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
Labels: cleanup

#540 Expand VmScan specs before refactoring VmScan
  spec/models/manageiq/providers/openstack/cloud_manager/vm_scan_spec.rb
Labels: smart state, test
