Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2019-01, with the labels that each got.

#423 Remove duplicated persister shared_options
  app/models/manageiq/providers/openstack/inventory/persister.rb
Labels: hammer/yes, refactoring

#426 Change FactoryGirl to FactoryBot
  spec/factories/orchestration_template.rb
  spec/models/manageiq/providers/openstack/cloud_manager/auth_key_pair_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_tenant_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_snapshot_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/flavor_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/host_aggregate_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/orchestration_stack_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/orchestration_template_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/provision/configuration_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/provision/volume_attachment_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/provision_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_helpers.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_worker_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_havana_errors_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/template_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/vnfd_template_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
  spec/models/manageiq/providers/openstack/identity_sync_mixin_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_custom_attributes_parsing_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_service_group_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_smart_state_analysis_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/orchestration_stack_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/refresh_worker_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/cloud_network_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/cloud_subnet_refresh_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/cloud_subnet_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/floating_ip_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/network_router_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/security_group_spec.rb
  spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser_spec.rb
  spec/models/metric/ci_mixin/capture_spec.rb
Labels: gaprindashvili/no, hammer/no

#425 [HAMMER] Remove legacy network collection from CloudManager graph refresh
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
  spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Labels: bug

#424 [GAPRINDASHVILI] Remove legacy network collection from CloudManager graph refresh
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
  spec/models/manageiq/providers/openstack/cloud_manager/stubbed_refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
Labels: bug

#427 [HAMMER] Targeted refresh: Collect tenant ems references last
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Labels: blocker, bug

#428 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#431 [Changelog] Update for Sprit 102
  CHANGELOG.md
Labels: documentation

#434 [Changelog] Update for Sprint 103
  CHANGELOG.md
Labels: documentation

#429 [GAPRINDASHVILI] Bump fog openstack
  manageiq-providers-openstack.gemspec
Labels: bug
