Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-04, with the labels that each got.

#574 CHANGELOG for Sprint 133
  CHANGELOG.md
Labels: documentation

#576 Update Network Refresh error logging for not-OpenStack provider
  app/models/manageiq/providers/openstack/refresh_parser_common/helper_methods.rb
Labels: bug, ivanchuk/yes, jansa/yes

#579 Handle Keystone service without a region
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Labels: bug

#578 [CloudTenant] Fix "Dangerous query method"
  app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
Labels: jansa/yes?

#580 parent is a method, not an association, and cannot be included
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
Labels: bug, jansa/yes?
