Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-01, with the labels that each got.

#544 Update CHANGELOG for Sprint 126
  CHANGELOG.md
Labels: documentation

#543 Subclass VmScan job as ManageIQ::Providers::Openstack::CloudManager::Scanning::Job
  app/models/manageiq/providers/openstack/cloud_manager/scanning.rb
  app/models/manageiq/providers/openstack/cloud_manager/scanning/job.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm_or_template_shared/scanning.rb
  spec/models/manageiq/providers/openstack/cloud_manager/vm_scan_spec.rb
Labels: refactoring, smart state

#552 Sprint 128 Changelog
  CHANGELOG.md
Labels: documentation

#550 [HAMMER] Fix targeted refresh for nested stacks and their resource relations
  app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb
  app/models/manageiq/providers/openstack/inventory/collector.rb
  app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Labels: bug

#551 [IVANCHUK] Fix targeted refresh for nested stacks and their resource relations
  app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb
  app/models/manageiq/providers/openstack/inventory/collector.rb
  app/models/manageiq/providers/openstack/inventory/collector/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_legacy_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Labels: bug

#555 Check for infra_ems before calculating block_storage_disk_capacity
  app/models/manageiq/providers/openstack/cloud_manager/availability_zone.rb
  spec/models/manageiq/providers/openstack/cloud_manager/availability_zone_spec.rb
Labels: bug
