Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-09, with the labels that each got.

#629 Check for ssl-no-validation string
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Labels: bug

#631 Remove executable bit from files that don't need it
  lib/manageiq/providers/openstack/legacy/test/event_monitor_example.rb
Labels: bug

#510 Fix Volume auto deletion with VM
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
Labels: bug

#626 Update DDF schema to version 2
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: enhancement

#633 [IVANCHUK] Cache metrics api call
  app/models/manageiq/providers/openstack/base_metrics_capture.rb
Labels: performance

#634 Fix bug where new providers are not reflected in the list
  app/models/manageiq/providers/openstack/cloud_manager.rb
  spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Labels: bug, jansa/yes?

#632 Ignore the tools/openstack_data directory in yaml lint
  .yamllint
Labels: technical debt

#637 Don't seed NotificationTypes in the main spec_helper
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_backup_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_snapshot_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/cloud_volume_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
  spec/spec_helper.rb
Labels: technical debt, test

#638 Use the tag_mapper from the core Persister
  app/models/manageiq/providers/openstack/inventory/persister.rb
Labels: refactoring

#639 Make the credentials required in the provider DDF
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: bug

#640 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: enhancement
