Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-06, with the labels that each got.

#591 Handle timeouts for unsupported services, as well as possible Neutron failure
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/handled_list.rb
  spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Labels: bug

#608 Move combined refresh workers to core
  app/models/manageiq/providers/openstack/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/openstack/infra_manager/refresh_worker.rb
  spec/models/manageiq/providers/openstack/infra_manager/refresh_worker_spec.rb
Labels: refactoring

#607 Delegate cloud_tenants to parent_manager from storage_manager
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
Labels: bug

#609 Set the monitor_running event to unblock the main thread
  app/models/manageiq/providers/openstack/event_catcher_mixin.rb
Labels: bug, jansa/yes?
