Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-11, with the labels that each got.

#666 Remodulize missed references to CloudVolumeSnapshot
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: bug

#662 Set the supports :auth_key_pair_create on the CloudManager
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: enhancement, kasparov/no

#667 Update Network Targeted refresh to skip not found network
  app/models/manageiq/providers/openstack/inventory/collector/target_collection.rb
Labels: bug

#644 Declared DDF schema for cloud volume creation and editing
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: enhancement, unmergeable
