Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-07, with the labels that each got.

#613 Move supports :create to Openstack provider repo
  app/models/manageiq/providers/openstack/cloud_manager/flavor.rb
Labels: bug, jansa/yes?

#614 Parse oslo.message in all events
  app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb
  app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb
  spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
Labels: bug

#615 Add @andyvesel to CODEOWNERS
  .github/CODEOWNERS
Labels: developer

#616 Consolidate event parsing
  app/models/manageiq/providers/openstack/cloud_manager/event_parser.rb
  app/models/manageiq/providers/openstack/cloud_manager/event_target_parser.rb
  app/models/manageiq/providers/openstack/event_parser_common.rb
  app/models/manageiq/providers/openstack/infra_manager/event_parser.rb
  app/models/manageiq/providers/openstack/network_manager/event_parser.rb
  app/models/manageiq/providers/openstack/network_manager/event_target_parser.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_parser.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser.rb
  spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser_spec.rb
  spec/support/ems_event_helper.rb
Labels: jansa/no, refactoring

#611 Split up the common DDF for infra and cloud
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: enhancement

#617 Use event host_uid_ems instead of doing a db query
  app/models/manageiq/providers/openstack/infra_manager/event_parser.rb
  spec/models/manageiq/providers/openstack/infra_manager/event_parser_spec.rb
Labels: refactoring

#610 bump more core extensions
  manageiq-providers-openstack.gemspec
Labels: dependencies

#618 Remove unneeded code
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: technical debt

#621 The vm_delete_snapshot method is missing a require
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug, jansa/yes?

#600 Cache metrics api call
  app/models/manageiq/providers/openstack/base_metrics_capture.rb
Labels: performance

#624 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement

#623 Rename the key_pairs collection to auth_key_pairs
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring
