Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-03, with the labels that each got.

#559 Add display name for cinder storage manager
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
Labels: technical debt

#560 Remove invalid partials from specs
  spec/models/manageiq/providers/openstack/infra_manager/orchestration_stack_spec.rb
  spec/models/manageiq/providers/openstack/openstack_stubs.rb
Labels: refactoring, test

#562 Fix not needed Events reloading after restart
  lib/manageiq/providers/openstack/legacy/events/openstack_ceilometer_event_monitor.rb
Labels: bug

#564 Remove classic refresh from Openstack InfraManager
  app/models/manageiq/providers/openstack/infra_manager.rb
  app/models/manageiq/providers/openstack/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/openstack/inventory/parser.rb
  app/models/manageiq/providers/openstack/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/openstack/refresh_parser_common/flavors.rb
  app/models/manageiq/providers/openstack/refresh_parser_common/images.rb
  app/models/manageiq/providers/openstack/refresh_parser_common/orchestration_stacks.rb
  config/settings.yml
  spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
Labels: cleanup

#566 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#567 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#569 remove rest of inventory object refresh
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
  app/models/manageiq/providers/openstack/network_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
Labels: cleanup

#570 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#571 Remove unused RefreshParserCommon::Images mixin
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
Labels: bug

#572 Remove unused ems_inv_to_hashes
  app/models/manageiq/providers/openstack/infra_manager/refresher.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/refresher.rb
Labels: cleanup

#573 If we fail to find a tenant don't return an Array
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Labels: bug
