Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-05, with the labels that each got.

#581 Implemented authentication_class selection logic based on authtype
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: enhancement

#568 Adjusted DDF schema for create/edit and validation
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: enhancement

#582 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#583 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#585 Fix Openstack service status section for infra node
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: bug

#556 Add STF Event monitor backend
  .travis.yml
  app/models/manageiq/providers/openstack/event_catcher_mixin.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
  config/settings.yml
  lib/manageiq/providers/openstack/legacy/events/openstack_stf_event_converter.rb
  lib/manageiq/providers/openstack/legacy/events/openstack_stf_event_monitor.rb
  lib/manageiq/providers/openstack/legacy/events/openstack_stf_event_receiver.rb
  lib/manageiq/providers/openstack/legacy/events/openstack_stf_event_test_receiver.rb
  lib/manageiq/providers/openstack/legacy/openstack_event_monitor.rb
  manageiq-providers-openstack.gemspec
  spec/legacy/events/openstack_stf_event_monitor_spec.rb
  tools/ci/before_install.sh
Labels: enhancement

#584 Ensure that the AMQP port gets properly to the validation in DDF
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: bug

#587 Don't require qpid_proton in gemspec
  .travis.yml
  manageiq-providers-openstack.gemspec
Labels: bug

#590 Refactor STF Event Monitor - service switch in manager mixin
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: refactoring

#596 Fix bash condition for services list
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: bug

#599 Do not call gettext on DDF form select option values
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: bug

#598 Add supports terminate feature
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb
  spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
Labels: bug, jansa/yes?
