Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2020-10, with the labels that each got.

#641 Add missing model display names
  app/models/manageiq/providers/openstack/cloud_manager/template.rb
  app/models/manageiq/providers/openstack/cloud_manager/volume_snapshot_template.rb
  app/models/manageiq/providers/openstack/cloud_manager/volume_template.rb
Labels: enhancement

#525 Add proxy support to Openstack
  app/models/manageiq/providers/openstack/cloud_manager/cloud_volume.rb
  app/models/manageiq/providers/openstack/helper_methods.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/baremetal_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/compute_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/event_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/handled_list.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/identity_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/image_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/introspection_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/metering_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/metric_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/multi_tenancy/base.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/network_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/nfv_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/orchestration_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/storage_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/volume_delegate.rb
  lib/manageiq/providers/openstack/legacy/openstack_handle/workflow_delegate.rb
Labels: enhancement

#646 Check qpid_proton installation on local machines before running tests
  spec/legacy/events/openstack_stf_event_monitor_spec.rb
Labels: developer, test

#645 Move VcrRecorder closer to the rake task
  lib/tasks_private/openstack.rake
  lib/tasks_private/vcr_recorder.rb
Labels: cleanup

#647 Update qpid_proton spec handling using exclude filter
  spec/legacy/events/openstack_stf_event_monitor_spec.rb
  spec/spec_helper.rb
Labels: technical debt, test

#648 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#588 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-openstack.gemspec
Labels: unmergeable

#649 Mark the CloudManager with supports :cloud_tenants
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: enhancement

#650 Fix StorageManager initialization
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug

#652 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#659 Expose supports :create_flavor on the CloudManager
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: enhancement
