Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2021-02, with the labels that each got.

#686 remove extraneous require thread
  lib/manageiq/providers/openstack/legacy/events/openstack_rabbit_event_monitor.rb
Labels: cleanup

#687 Pass CloudVolumeType#name in the CloudVolume form instead of type
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: bug

#692 Replace Host.validate_destroy with supports?(:destroy)
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: refactoring

#689 Convert `supports_#{op}?` to `supports?(op)`
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/cloud_manager/base_template.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations/guest.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations/relocation.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations/snapshot.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/resize.rb
  app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb
  spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
Labels: refactoring
