Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2021-08, with the labels that each got.

#726 Add supports :storage_manager and block_storage_manager function to Openstack
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: enhancement

#728 Make sure admin_state_up isn't `nil`
  app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb
Labels: bug

#730 Fix the template STI class for openstack subclasses
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Labels: bug, morphy/yes
