Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2021-10, with the labels that each got.

#736 Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
  .travis.yml
Labels: test

#733 Convert AuthKey operations to SupportsFeatureMixin
  app/models/manageiq/providers/openstack/cloud_manager/auth_key_pair.rb
  spec/models/manageiq/providers/openstack/cloud_manager/auth_key_pair_spec.rb
Labels: technical debt

#740 Subclass CloudObjectStore(Container|Object) models under Openstack SwiftManager
  app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_container.rb
  app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_object.rb
Labels: bug
