Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2021-01, with the labels that each got.

#672 Make the snapshot description field required
  app/models/manageiq/providers/openstack/cloud_manager/vm.rb
Labels: bug

#674 Move environment builder from core
  spec/tools/environment_builders/openstack.rb
  spec/tools/environment_builders/openstack/helper_methods.rb
  spec/tools/environment_builders/openstack/interaction_methods.rb
  spec/tools/environment_builders/openstack/services/base_data.rb
  spec/tools/environment_builders/openstack/services/compute/builder.rb
  spec/tools/environment_builders/openstack/services/compute/data.rb
  spec/tools/environment_builders/openstack/services/identity/builder.rb
  spec/tools/environment_builders/openstack/services/identity/builder/keystone_v2.rb
  spec/tools/environment_builders/openstack/services/identity/builder/keystone_v3.rb
  spec/tools/environment_builders/openstack/services/identity/data/keystone_v2.rb
  spec/tools/environment_builders/openstack/services/identity/data/keystone_v3.rb
  spec/tools/environment_builders/openstack/services/image/builder.rb
  spec/tools/environment_builders/openstack/services/image/data.rb
  spec/tools/environment_builders/openstack/services/network/builder.rb
  spec/tools/environment_builders/openstack/services/network/builder/base.rb
  spec/tools/environment_builders/openstack/services/network/builder/neutron.rb
  spec/tools/environment_builders/openstack/services/network/builder/nova.rb
  spec/tools/environment_builders/openstack/services/network/data/neutron.rb
  spec/tools/environment_builders/openstack/services/network/data/nova.rb
  spec/tools/environment_builders/openstack/services/orchestration/builder.rb
  spec/tools/environment_builders/openstack/services/orchestration/data.rb
  spec/tools/environment_builders/openstack/services/orchestration/test_template.yml
  spec/tools/environment_builders/openstack/services/storage/builder.rb
  spec/tools/environment_builders/openstack/services/storage/data.rb
  spec/tools/environment_builders/openstack/services/volume/builder.rb
  spec/tools/environment_builders/openstack/services/volume/data.rb
  spec/tools/environment_builders/openstack/tests/interaction_methods_spec.rb
  spec/tools/environment_builders/openstack_environments.rb
  spec/tools/environment_builders/openstack_install_environments.rb
  spec/tools/environment_builders/openstack_vcr.sh
Labels: tools

#673 Move SwiftManager to Openstack plugin
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector/storage_manager.rb
  app/models/manageiq/providers/openstack/inventory/collector/storage_manager/swift_manager.rb
  app/models/manageiq/providers/openstack/inventory/parser/storage_manager.rb
  app/models/manageiq/providers/openstack/inventory/parser/storage_manager/swift_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/storage_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/storage_manager/swift_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/swift_manager/refresher.rb
  app/models/manageiq/providers/openstack/swift_manager_mixin.rb
Labels: technical debt

#675 Fix the path to the environment_builders
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
Labels: bug, test

#676 Add support for the create_network_router feature for network mgr
  app/models/manageiq/providers/openstack/network_manager.rb
Labels: enhancement

#678 Move logger initialization and configuration into plugins
  config/settings.yml
  lib/manageiq/providers/openstack/engine.rb
Labels: refactoring

#681 Fix VMDBLogger NoMethodError "instrument"
  lib/manageiq/providers/openstack/engine.rb
Labels: bug

#679 Adjust the support features and ddf schema after CloudVolume remodel
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: bug, kasparov/no

#682 Update manageiq-style
  .codeclimate.yml
Labels: developer

#677 Don't subclass from core cinder/swift managers
  app/models/manageiq/providers/openstack/cinder_manager_mixin.rb
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/storage_collections.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb
  app/models/manageiq/providers/openstack/swift_manager_mixin.rb
Labels: cleanup
