Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2021-04, with the labels that each got.

#698 Fix default_api_port used in cloud_manager_spec
  spec/models/manageiq/providers/openstack/cloud_manager_spec.rb
Labels: test

#699 Fix domain_id params / verify key mismatch
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: bug, kasparov/yes?, lasker/yes?

#700 Don't stub authentication_status_ok? in event_catcher_spec
  spec/models/manageiq/providers/openstack/cloud_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/event_catcher_spec.rb
Labels: refactoring, test

#702 Extend error catching in detect_service for tenant
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Labels: bug

#701 Fix service detection if there is no admin tenant
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Labels: bug

#704 Make it easier to subclass the Openstack refresh classes
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Labels: enhancement

#707 Add CloudVolume supports update
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: technical debt

#705 Don't hardcode STI class in refresh
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/storage_collections.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb
Labels: refactoring

#709 Remove unused validate_update_volume
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
  spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_spec.rb
Labels: technical debt
