Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2021-03, with the labels that each got.

#693 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#685 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-openstack_cloud_manager_event_catcher.target
  build/systemd_units/manageiq-providers-openstack_cloud_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-openstack_cloud_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-openstack_cloud_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-openstack_cloud_manager_refresh.target
  build/systemd_units/manageiq-providers-openstack_cloud_manager_refresh@.service
  build/systemd_units/manageiq-providers-openstack_infra_manager_event_catcher.target
  build/systemd_units/manageiq-providers-openstack_infra_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-openstack_infra_manager_metrics_collector.target
  build/systemd_units/manageiq-providers-openstack_infra_manager_metrics_collector@.service
  build/systemd_units/manageiq-providers-openstack_infra_manager_refresh.target
  build/systemd_units/manageiq-providers-openstack_infra_manager_refresh@.service
  build/systemd_units/manageiq-providers-openstack_network_manager_event_catcher.target
  build/systemd_units/manageiq-providers-openstack_network_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-openstack_storage_manager_cinder_manager_event_catcher.target
  build/systemd_units/manageiq-providers-openstack_storage_manager_cinder_manager_event_catcher@.service
Labels: technical debt

#690 Implemented DDF for cloud subnets and added support mixin call
  app/models/manageiq/providers/openstack/network_manager.rb
  app/models/manageiq/providers/openstack/network_manager/cloud_subnet.rb
Labels: enhancement

#696 Fix for the OpenStack port always being nil and defaulting to 5000
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: bug
