Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2021-12, with the labels that each got.

#757 converting supported_for_create to supports :create
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/provider.rb
Labels: enhancement

#758 Don't hard code cloud_tenant STI type
  app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Labels: bug

#759 Add fields for security groups form
  app/models/manageiq/providers/openstack/network_manager/security_group.rb
Labels: enhancement

#760 Use the snapshots collection from core
  app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Labels: refactoring
