Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2022-06, with the labels that each got.

#802 Exporting Strings
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug, internationalization

#803 Exporting Strings
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: bug, internationalization, najdorf/yes?

#804 Move all valid ems in zone to mixin
  app/models/manageiq/providers/openstack/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/cloud_manager/event_catcher/runner.rb
  app/models/manageiq/providers/openstack/event_catcher_mixin.rb
  app/models/manageiq/providers/openstack/event_catcher_runner_mixin.rb
  app/models/manageiq/providers/openstack/infra_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/infra_manager/event_catcher/runner.rb
  app/models/manageiq/providers/openstack/network_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/network_manager/event_catcher/runner.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher/runner.rb
Labels: refactoring, najdorf/yes?

#808 Add timeout-minutes to setup-ruby job
  .github/workflows/ci.yaml
Labels: developer
