Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2022-07, with the labels that each got.

#807 Fix ceilometer endpoint creation
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug

#805 Improve event monitor available check
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/event_catcher_mixin.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
  app/models/manageiq/providers/openstack/network_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  spec/models/manageiq/providers/openstack/cloud_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/event_catcher_spec.rb
Labels: enhancement

#809 Use EvmSpecHelper.local_server
  spec/models/manageiq/providers/openstack/cloud_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_helpers.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_havana_errors_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/host_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/metrics_capture_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
  spec/models/manageiq/providers/openstack/network_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_target_parser_spec.rb
  spec/models/metric/ci_mixin/capture_spec.rb
Labels: technical debt, test

#810 Convert validates to supports
  app/models/manageiq/providers/openstack/cloud_manager/template.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: technical debt

#811 fix issue finding parallel
  lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb
Labels: bug

#812 Fixed cloud provider form clearable select field
  app/models/manageiq/providers/openstack/cloud_manager.rb
Labels: bug

#813 Removing Memoization
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: bug, najdorf/yes?
