Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2022-05, with the labels that each got.

#796 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#793 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#794 rename CloudVolume#attach_volume to attach
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume/operations.rb
Labels: enhancement

#789 Improve OpenStack operations error parsing
  app/models/manageiq/providers/openstack/helper_methods.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume/operations.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_backup.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_snapshot.rb
Labels: enhancement

#797 Add custom schema fields to Openstack attach cloud volume form
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: enhancement

#800 update cloud volume snapshot specs
  spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_snapshot_spec.rb
Labels: enhancement

#801 Use add_cloud_collection for cinder_manager
  app/models/manageiq/providers/openstack/inventory/persister/storage_manager/cinder_manager.rb
Labels: cleanup

#798 Convert host operations to supports
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: refactoring
