Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2022-03, with the labels that each got.

#783 Minor Cleanup child manager init/ensure_
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/swift_manager_mixin.rb
Labels: technical debt

#784 Refactor AuthKeyPair.raw_create_key_pair
  app/models/manageiq/providers/openstack/cloud_manager/auth_key_pair.rb
Labels: refactoring

#786 Fix notification error
  app/models/manageiq/providers/openstack/storage_manager/swift_manager/cloud_object_store_container.rb
Labels: bug, najdorf/yes?
