Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2022-08, with the labels that each got.

#815 Loosen the version requirement for parallel
  manageiq-providers-openstack.gemspec
Labels: dependencies

#814 Record refresh VCRs rake task
  lib/tasks_private/openstack.rake
  lib/tasks_private/vcr_recorder.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher.yml
Labels: developer, test

#817 rename Vm Operation context
  spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
Labels: technical debt

#822 Add microstack target refresher specs
  lib/tasks_private/openstack.rake
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_admin.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_network_target.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_port_target.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_router_target.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_tenant_target.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_vm_target.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/refresher_volume_target.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher/vm_target.yml
Labels: enhancement, test

#818 Add spec tests to microstack refresher spec
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_havana_errors_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_spec.rb
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_keystone_v3_fast_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_network_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_port_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_router_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_stack_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_tenant_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_vm_targeted_refresh.yml
  spec/vcr_cassettes/manageiq/providers/openstack/cloud_manager/refresher_rhos_liberty_volume_targeted_refresh.yml
Labels: enhancement, test
