Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2022-02, with the labels that each got.

#770 Remove Hakiri
  README.md
Labels: cleanup, developer

#772 Fix storage manager edit
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: bug

#774 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-openstack.gemspec
  tools/ci/before_install.sh
Labels: developer, test

#775 Restore deleted before_install
  bin/before_install
Labels: developer, test

#773 Fixed cloud volume minimum size
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
Labels: bug

#777 Add Build History Graph to README.md
  README.md
Labels: developer, test

#771 Fix CloudVolume Create - DDF sends cloud_tenant_id not cloud_tenant record
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
  spec/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume_spec.rb
Labels: bug

#778 Move HostAggregate.*_queue methods to core
  app/models/manageiq/providers/openstack/cloud_manager/host_aggregate.rb
Labels: refactoring

#780 The Openstack NetworkManager cannot be added standalone
  app/models/manageiq/providers/openstack/network_manager.rb
Labels: bug, najdorf/yes?

#782 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
