Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2022-10, with the labels that each got.

#827 Subclass Snapshot under Openstack::CloudManager
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/cloud_manager/snapshot.rb
Labels: bug

#829 Upgrade workflows to actions/checkout@v3
  .github/workflows/ci.yaml
Labels: enhancement, test

#828 vm resize feature refactored to work with ddf
  app/models/manageiq/providers/openstack/cloud_manager/vm/resize.rb
  spec/models/manageiq/providers/openstack/cloud_manager/vm_spec.rb
Labels: enhancement
