Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2023-04, with the labels that each got.

#845 Allow a missing Snapshot#vm_or_template_id
  app/models/manageiq/providers/openstack/inventory/persister/definitions/cloud_collections.rb
Labels: bug, petrosian/yes?

#842 Provider validate credentials
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
  app/models/manageiq/providers/openstack/infra_manager/host/operations.rb
  app/models/manageiq/providers/openstack/manager_mixin.rb
Labels: bug

#846 Drop validate_credentials_task
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: cleanup

#847 Use standard verify_credentials
  app/models/manageiq/providers/openstack/infra_manager.rb
Labels: cleanup

#848 Drop lib/gem-name.rb in favor of lib/gem/name.rb
  lib/manageiq-providers-openstack.rb
  lib/manageiq/providers/openstack.rb
  spec/spec_helper.rb
Labels: enhancement
