Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2023-03, with the labels that each got.

#839 use default verify_credentials implementation
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: refactoring

#840 Allow overrides of Openstack::ProvisionWorkflow class
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
Labels: bug, petrosian/yes?

#836 Introducing params_for_update schema fields for Hosts
  app/models/manageiq/providers/openstack/infra_manager/host.rb
Labels: enhancement, unmergeable
