Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2024-02, with the labels that each got.

#871 Drop require_nested and include_concern
  app/models/manageiq/providers/openstack/cloud_manager.rb
  app/models/manageiq/providers/openstack/cloud_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/cloud_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/openstack/cloud_manager/orchestration_stack.rb
  app/models/manageiq/providers/openstack/cloud_manager/provision.rb
  app/models/manageiq/providers/openstack/cloud_manager/provision_workflow.rb
  app/models/manageiq/providers/openstack/cloud_manager/refresh_worker.rb
  app/models/manageiq/providers/openstack/cloud_manager/scanning.rb
  app/models/manageiq/providers/openstack/cloud_manager/template.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm/operations.rb
  app/models/manageiq/providers/openstack/cloud_manager/vm_or_template_shared.rb
  app/models/manageiq/providers/openstack/cloud_manager/vnf.rb
  app/models/manageiq/providers/openstack/infra_manager.rb
  app/models/manageiq/providers/openstack/infra_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/infra_manager/host.rb
  app/models/manageiq/providers/openstack/infra_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/openstack/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/openstack/inventory.rb
  app/models/manageiq/providers/openstack/inventory/collector.rb
  app/models/manageiq/providers/openstack/inventory/collector/storage_manager.rb
  app/models/manageiq/providers/openstack/inventory/parser.rb
  app/models/manageiq/providers/openstack/inventory/parser/storage_manager.rb
  app/models/manageiq/providers/openstack/inventory/persister.rb
  app/models/manageiq/providers/openstack/inventory/persister/storage_manager.rb
  app/models/manageiq/providers/openstack/network_manager.rb
  app/models/manageiq/providers/openstack/network_manager/cloud_network.rb
  app/models/manageiq/providers/openstack/network_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/cloud_volume.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager/event_catcher.rb
  app/models/manageiq/providers/openstack/storage_manager/swift_manager.rb
Labels: technical debt, rails7

#872 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#873 Delete an unused NetworkManager MetricsCollectorWorker Runner class
  app/models/manageiq/providers/openstack/network_manager/metrics_collector_worker/runner.rb
Labels: cleanup

#874 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
