Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2025-01, with the labels that each got.

#896 [RADJABOV] Lockdown Ruby version to Ruby 3.3
  .github/workflows/ci.yaml
Labels: test

#895 Delegate refresh_ems class method to parent cloud manager
  app/models/manageiq/providers/openstack/network_manager.rb
  app/models/manageiq/providers/openstack/storage_manager/cinder_manager.rb
  config/settings.yml
Labels: bug, radjabov/yes?

#900 Inherit renovate config from a central location
  renovate.json
Labels: developer
