Repository ManageIQ/manageiq-providers-openstack, pull requests merged in 2025-07, with the labels that each got.

#915 Switch to use VcrSecrets helper from core
  .gitignore
  config/secrets.defaults.yml
  lib/manageiq/providers/openstack/engine.rb
  spec/config/secrets.defaults.yml
  spec/models/manageiq/providers/openstack/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#916 Port should be an int in vcr secrets
  spec/config/secrets.defaults.yml
  spec/models/manageiq/providers/openstack/infra_manager/refresher_rhos_juno_spec.rb
Labels: test

#914 Fix CloudTenant creation invalid parent_id
  app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb
Labels: bug, spassky/yes?

#917 Drop to_s on engine paths
  lib/manageiq/providers/openstack/engine.rb
Labels: technical debt
